### ISSUE TITLE
How to center images with different unknow height vertically?

### ISSUE THREAD

**Issue by Tinple** [voronianski/react-swipe#68]
```
<ReactSwipe
  continuous={false}
  disableScroll={true}
  transitionEnd={this.transitionEnd}
  startSlide={start}
  style={{verticalAlign: 'middle', display: 'table-cell'}}
  key={images.length}
>
{
  images.map(function(image, index) {
    return (
       <img src={image} alt="" key={index} />
    );
  })
}
</ReactSwipe>
```

The `images` contains different unknow height image, I want to center the image but fail. It seems the image container has the max height of the images. How can I do it?

**Comment by Tinple** [comment]
Use `flexbox` can solve my problem, but is there a way to set `wrapper` style?

**Comment by saidmoya12** [comment]
Wrap the image into a relative div

``` js
//react
 return (
     <div className="wrapperItem">
       <img src={image} alt="" key={index} />
    </div>
 );
```

``` css
/*style*/
.wrapperItem{
    position relative
}
.wrapperItem img{
   position: absolute;
   left: 50%; top: 50%;
   transform: translate(-50%, -50%);
}
```
